//Un comité esta integrado por dos o más personas. Una persona puede o no pertenecer a comités. Cada comité tiene un coordinador que forma parte del comité y una misma
persona puede coordinar más de un comité

@startuml EJERCICIO_06

class persona 
class comite 
class coordinador

comite "1" o-- "2 ... *" persona
comite "1" o-- "1" coordinador
@enduml