//Un laboratorio tiene una diversidad de equipos, pero solamente un laboratorio nuclear puede tener equipos nucleares

@startuml EJERCICIO_08

class Laboratorio 
class Laboratorio_Nuclear extends Laboratorio
class Equipo
class Equipo_Nuclear extends Equipo

Laboratorio "1" o-- "1 ... *" Equipo
Laboratorio_Nuclear "1" o-- "1 ...* "Equipo_Nuclear

@enduml