//Suponga dos triángulos con un lado común. Hacer un diagrama de objetos donde: “un
punto pertenece a uno o más polígonos”

@startuml EJERCICIO_C_02

object "T1 : Poligono" as T1
object "T2 : Poligono" as T2

object "P1 : Punto" as P1 {
    coord_x = 0
    coord_y = 0
}

object "P2 : Punto" as P2 {
    coord_x = 1
    coord_y = 0
}

object "P3 : Punto" as P3 {
    coord_x = 1
    coord_y = 1
}

object "P4 : Punto" as P4 {
    coord_x = -1
    coord_y = 0
}

object "P5 : Punto" as P5 {
    coord_x = -1
    coord_y = 1
}

'T1

T1 -l- P1
T1 -r- P2
T1 -u- P3

'T2

T2 -r- P1
T2 -l- P4
T2 -u- P5

@enduml