//Un trabajo de grado especial (TEG) y un trabajo de grado de maestría (TGM) son
trabajos de investigación. Todo trabajo de investigación es dirigido por uno o a lo sumo dos profesores que juegan el rol de tutor. Un mismo profesor puede dirigir varios trabajos de investigación. Un TGM siempre se realiza de manera individual, es decir, un solo estudiante de postgrado mientras que un TEG puede ser realizado por uno o dos estudiantes de pregrado.

@startuml EJERCICIO_10

class Trabajo_de_investigacion
class Trabajo_de_grado_especial extends Trabajo_de_investigacion
class Trabajo_de_grado_de_maestria extends Trabajo_de_investigacion
class estudiante
class profesor

profesor "1,2" --> "1" Trabajo_de_investigacion: "dirige"

estudiante "1" --> "1" Trabajo_de_grado_de_maestria: realiza

estudiante "1,2" --> "1" Trabajo_de_grado_especial: realiza

@enduml