// Un disco duro esta formado por pistas, y las pistas están formadas por sectores

@startuml EJERCICIO_04

class disco_duro 
class pista
class sectores

disco_duro "1" *-- "1 ... *" pista 
pista "1" *-- "1 ... *"sectores 

@enduml