//Suponga que un documento gráfico está compuesto de hojas. Cada hoja contiene un
objeto dibujo. Un objeto dibujo puede ser: texto, figura 2D, o grupo. Un grupo consta de al menos dos objetos dibujo. Un objeto de dibujo puede ser a lo sumo miembro de un
grupo. Una figura 2D puede ser circulo o cuadrado.

@startuml EJERCICIO_11

class documento_grafico
class hojas
class dibujo
class texto extends dibujo
class figura_2D extends dibujo
class grupo
class circulo extends figura_2D
class cuadrado extends figura_2D

documento_grafico "1" *-- "*" hojas
hojas o-- dibujo 

dibujo --|> grupo

dibujo "2...* {Para cada dibujo, un solo grupo}" --> "1" grupo : "Es miembro"

@enduml