//Diagrama de Objetos 

@startuml EJERCICIO_F_02

object "J1 : Jugador" as J1{
  telefeno = 04121234567
  nombre = "Juan Pérez"
  direccion = "Calle 1"
  numero = 1
  posicion = "Armador"
}

object "J2 : Jugador" as J2{
  telefeno = 04121234568
  nombre = "María Rodríguez"
  direccion = "Calle 2"
  numero = 2
  posicion = "Rematador exterior"
}

object "J3 : Capitan" as J3{
  telefeno = 04121234569
  nombre = "Pedro Gómez"
  direccion = "Calle 3"
  numero = 3
  posicion = "Rematador central"
}

object "J4 : Jugador" as J4{
  telefeno = 04121234570
  nombre = "Ana Sánchez"
  direccion = "Calle 4"
  numero = 4
  posicion = "Rematador exterior"
}

object "J5 : Jugador" as J5{
  telefeno = 04121234571
  nombre = "Luis García"
  direccion = "Calle 5"
  numero = 5
  posicion = "Líbero"
}

object "J6 : Capitan" as J6{
  telefeno = 04121234572
  nombre = "Carolina Fernández"
  direccion = "Calle 6"
  numero = 6
  posicion = "Especialista defensivo"
}

object "EN1 : Entrenador" as EN1{
    telefeno = 04121234576
    nombre = "José Buonarroti"
    direccion = "Calle 156"
    acreditacion = "A"
    experiencia = 4
}

object "EN2 : Entrenador" as EN2{
    telefeno = 04121334410
    nombre = "Rómulo Gallegos"
    direccion = "Calle 616"
    acreditacion = "B"
    experiencia = 5
}

object "E1 : Equipo" as E1 {
    nombre = "Venezuela"
    registro = 844124
}

object "E2 : Equipo" as E2 {
    nombre = "Colombia"
    registro = 151545
}

object "JUE : Juego" as JUE {
    localidad = "Chile"
    puntuacion = "3:0"
}

E1 --- J1
E1 --- J2
E1 --- J3
E1 -l- EN1 

E2 --- J4
E2 --- J5
E2 --- J6
E2 -r- EN2

JUE -l- E1
JUE -r- E2 

@enduml