/'Muestre en un diagrama de secuencias los detalles de las siguientes instrucciones escritas en
Java:

1. (miLista.getItem()).hacerAlgo()
2. miColeccion.getEstudiante(i).getNombre()
'/

@startuml EJERCICIO_A_1

actor a
participant ": miColeccion" as miColeccion
participant ": estudiante" as estudiante  

miColeccion -> estudiante : getEstudiante(i)
activate estudiante

estudiante --> a : getNombre()
deactivate estudiante

@enduml