/'Muestre en un diagrama de secuencias los detalles de las siguientes instrucciones escritas en
Java:

1. (miLista.getItem()).hacerAlgo()
'/

@startuml EJERCICIO_A_1

actor a
participant ": milista" as milista
participant ": item" as item  

milista -> item : getItem()
activate item

item --> a : hacerAlgo()
deactivate item

@enduml