/'
CREAR DIAGRAMA DE COMUNICACIÓN

public class Registro {
    private CatalogoProductos catalogo;
    private Venta venta;
    public Registro(CatalogoProductos cp) {...}
    public void finalizarVenta() {...}
    public void crearNuevaVenta() {...}
    public void introducirArticulo(ArticuloID id, int cant) {
        EspecificacionProducto espec = catalogo.getEspecificacion(id);
        venta.crearLineaVenta(espec, cant);
    }
}
public class Venta {
    private Date fechaHora = new Date();
    private List lineasVenta = new ArrayList();
    ...
    public void crearLineaVenta(espec, cant){
        lineasVenta.añadir(new LineaVenta(espec, cant));
    }
}
'/

@startuml EJERCICIO_H

allowmixing
skinparam actorStyle hollow
skinparam noteBackgroundColor transparent
skinparam noteBorderColor transparent
hide members

object "registro : Registro" as registro
object "venta : Venta" as venta
actor user

user -> registro 
note on link
1 : crearNuevaVenta()
2 : introducirArticulo(ArticuloID id, int cant)
4 : finalizarVenta()
end note

registro -d-> venta
note on link
3 : crearLineaVenta(espec, cant)
end note

@enduml